AthenZ/k8s-athenz-istio-auth

- main.go
- pkg/servicerole/servicerole.go
- pkg/servicerole/servicerole_test.go
> Add support for path in service role

- main.go
- pkg/controller/controller.go
- pkg/servicerole/servicerole.go
- pkg/servicerole/servicerole_test.go
> Add dns-suffix parameter

- .travis.yml
- README.md
> Configure only master branch to build after pull request merge, add build link

- pkg/controller/controller.go
- pkg/istio/clusterrbacconfig/clusterrbacconfig.go
- pkg/istio/clusterrbacconfig/clusterrbacconfig_test.go
- pkg/istio/servicerole/servicerole.go
- pkg/istio/servicerole/servicerole_test.go
- pkg/istio/servicerolebinding/servicerolebinding.go
- pkg/istio/servicerolebinding/servicerolebinding_test.go
> Remove client from istio mgr structs

- k8s/clusterrole.yaml
> Update cluster role to explicit istio resources, add athenz domain, service list watch

- pkg/athenz/model.go
- pkg/athenz/model_test.go
- pkg/istio/rbac/v1/provider.go
- pkg/istio/rbac/v1/provider_test.go
> Fix the order of model.Config output list and add provider unit tests

- go.mod
- go.sum
- pkg/apis/athenz/v1/types.go
> Replace deepcopy library

- main.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/istio/onboarding/controller.go
- pkg/istio/onboarding/controller_test.go
> Add resync cron for athenz domain and cluster rbac config

- go.mod
- go.sum
- main.go
- pkg/athenz/model.go
- pkg/athenz/util.go
- pkg/athenz/util_test.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/istio/onboarding/controller.go
- pkg/istio/onboarding/controller_test.go
- pkg/istio/processor/controller.go
- pkg/istio/processor/controller_test.go
- pkg/istio/rbac/common/servicerole.go
- pkg/istio/rbac/common/servicerole_test.go
- pkg/istio/rbac/common/servicerolebinding.go
- pkg/istio/rbac/common/servicerolebinding_test.go
- pkg/istio/rbac/v1/provider.go
- pkg/istio/rbac/v1/provider_test.go
- pkg/log/log.go
> Add logging framework, move utils to athenz pkg

- README.md
- k8s/deployment.yaml
> Remove sia containers from deployment

- README.md
> Remove sia references from readme, update parameter list

- main.go
- pkg/controller/controller.go
- pkg/istio/onboarding/controller.go
- pkg/istio/processor/controller.go
- pkg/istio/rbac/common/servicerole.go
- pkg/istio/rbac/common/servicerolebinding.go
- pkg/istio/rbac/v1/provider.go
- pkg/log/log.go
- pkg/log/log_test.go
> Add caller info prefix to log

- pkg/controller/controller.go
- pkg/controller/controller_test.go
> Fix the athenz domain key to treat cluster scope

- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/istio/onboarding/controller.go
- pkg/istio/processor/controller.go
- pkg/istio/processor/controller_test.go
- pkg/istio/rbac/common/servicerole.go
- pkg/istio/rbac/common/servicerole_test.go
- pkg/istio/rbac/common/servicerolebinding.go
- pkg/istio/rbac/common/servicerolebinding_test.go
- pkg/istio/rbac/v1/provider.go
- pkg/istio/rbac/v1/provider_test.go
> Handle underscore in roles and suppress warnings

- test/integration/framework/framework.go
- test/integration/main_test.go
> Add global framework object for integration tests

- README.md
- main.go
- pkg/controller/controller.go
- pkg/istio/rbac/common/servicerolebinding.go
- pkg/istio/rbac/common/servicerolebinding_test.go
- pkg/istio/rbac/v1/provider.go
- pkg/istio/rbac/v1/provider_test.go
- test/integration/authz_v1_test.go
- test/integration/fixtures/fixtures.go
- test/integration/framework/framework.go
> Add support for jwt authz in srb

- pkg/istio/rbac/common/servicerolebinding.go
- pkg/istio/rbac/common/servicerolebinding_test.go
- pkg/istio/rbac/common/util.go
- pkg/istio/rbac/v1/provider.go
- pkg/istio/rbac/v1/provider_test.go
> Add role cert spiffe in serviceRoleBinding

- pkg/athenz/model.go
- pkg/athenz/model_test.go
- pkg/controller/controller.go
> process trust domain for service role binding

- .travis.yml
- pkg/istio/authorizationpolicy/controller.go
- pkg/istio/authorizationpolicy/controller_test.go
- pkg/istio/rbac/v2/provider.go
- pkg/istio/rbac/v2/provider_test.go
> Add sync error check, add length check for request principals append

- main.go
- pkg/istio/rbac/common/util.go
- pkg/istio/rbac/common/util_test.go
- pkg/istio/rbac/v2/provider.go
> fix domain sync issue, restructure dry run folders

- pkg/istio/rbac/v2/provider.go
- pkg/istio/rbac/v2/provider_test.go
> Adding logic to drop query parameters when using Authz Policy

- pkg/istio/rbac/common/util.go
> update resource version before update action

- main.go
- pkg/controller/controller.go
- pkg/istio/authorizationpolicy/controller.go
- pkg/istio/authorizationpolicy/controller_test.go
> Handle services which are flipping from AP->SR/SRB and SR/SRB->AP

- pkg/istio/rbac/common/util.go
- pkg/istio/rbac/v2/provider.go
> Fixing bug for Service Roles when svc==*

- .travis.yml
- test/integration/authz_v1_test.go
> Move integration tests to script section

- pkg/athenz/model.go
- pkg/athenz/model_test.go
- pkg/istio/rbac/common/util.go
- pkg/istio/rbac/common/util_test.go
- pkg/istio/rbac/v2/provider.go
- pkg/istio/rbac/v2/provider_test.go
> Adding support for Athenz Groups

- pkg/controller/controller.go
- pkg/istio/authorizationpolicy/controller.go
- pkg/istio/authorizationpolicy/controller_test.go
- pkg/istio/rbac/interface.go
- pkg/istio/rbac/v1/provider.go
- pkg/istio/rbac/v1/provider_test.go
- pkg/istio/rbac/v2/provider.go
- pkg/istio/rbac/v2/provider_test.go
@mdhume @bhaskaramVaranasi @mcieplak 
> Changing workload selector label from svc to app for AP

- pkg/istio/authorizationpolicy/controller_test.go
- pkg/istio/rbac/v2/provider.go
- pkg/istio/rbac/v2/provider_test.go
@mcieplak @RuiGuo34 @mdhume 
Similar to the SRB Logic:
- https://github.com/yahoo/k8s-athenz-istio-auth/blob/master/pkg/istio/rbac/v1/provider.go#L45
- https://github.com/yahoo/k8s-athenz-istio-auth/blob/master/pkg/istio/rbac/v1/provider.go#L76
- https://github.com/yahoo/k8s-athenz-istio-auth/blob/fd5136d1d5bfba930da02a0e08ae6c81df85a4b0/pkg/istio/rbac/common/servicerolebinding.go#L59
> Changing principal value for role certificate in AP

- main.go
- pkg/athenz/model.go
- pkg/athenz/model_test.go
- pkg/controller/controller.go
- pkg/istio/authorizationpolicy/controller.go
- pkg/istio/authorizationpolicy/controller_test.go
- pkg/istio/onboarding/controller.go
- pkg/istio/rbac/common/util.go
- pkg/istio/rbac/common/util_test.go
- pkg/istio/rbac/v2/provider.go
- pkg/istio/rbac/v2/provider_test.go
- test/integration/fixtures/fixtures.go
- test/integration/framework/framework.go
> Adding logic for Combination Policies

- screwdriver.yaml
Add screwdriver.yaml for CI/CD - To build and test
> Add screwdriver.yaml for CI/CD

- pkg/controller/controller.go
- pkg/istio/authorizationpolicy/controller.go
- screwdriver.yaml
- test/integration/go.mod
Fix SD Pipeline and make integration test code compatible
> Set GOPATH env variable in screwdriver.yaml

- main.go
- pkg/controller/controller.go
- pkg/istio/authorizationpolicy/controller.go
- pkg/istio/authorizationpolicy/controller_test.go
- pkg/istio/rbac/common/servicerolebinding.go
- pkg/istio/rbac/common/util.go
- pkg/istio/rbac/common/util_test.go
- pkg/istio/rbac/v2/provider.go
- pkg/istio/rbac/v2/provider_test.go
- test/integration/framework/framework.go
> make admin domain an array
